/**
 * All Hebrew UI copy in one module (architecture §1: Hebrew RTL UI, English code).
 * Keeping copy centralized makes RTL/locale review a single-file pass.
 */
export const S = {
  appName: "iHelp",
  tagline: "מבקשים עזרה — והעוזרים מגיעים אליכם",

  landing: {
    lead: "במקום לחפש איש מקצוע ולהתקשר לכולם — מפרסמים בקשה אחת, ועוזרים מאומתים בסביבה מציעים סיוע ומתחרים על המחיר. בתשלום או בהתנדבות, ותמיד עם אדם מאומת בצד השני.",
    howTitle: "איך זה עובד",
    steps: [
      { n: "1", title: "מפרסמים בקשה", body: "מתארים מה צריך, מצרפים תמונה ובוחרים מיקום — לוקח דקה." },
      { n: "2", title: "מקבלים הצעות", body: "עוזרים מאומתים בסביבה מציעים עזרה, כל אחד עם המחיר שלו — או בהתנדבות." },
      { n: "3", title: "בוחרים ומדרגים", body: "בוחרים את ההצעה הטובה ביותר, מתאמים, ומדרגים בסיום." },
    ],
    trustTitle: "בנוי על אמון",
    trust: [
      { title: "אימות דו-צדדי", body: "כל מי שמתנהל באתר — מבקש ועוזר כאחד — עובר אימות זהות מול מנהל." },
      { title: "דירוגים אמיתיים", body: "כל עבודה מסתיימת בדירוג. המוניטין נבנה מעבודה אמיתית." },
      { title: "מחיר הוגן", body: "העוזרים מתחרים על המחיר — אתם בוחרים את מה שמתאים לכם." },
    ],
    ctaTitle: "צריכים עזרה, או רוצים לעזור?",
    emergencyNote: "במצב חירום",
  },

  nav: {
    requests: "בקשות עזרה",
    myRequests: "הבקשות שלי",
    myOffers: "ההצעות שלי",
    profile: "הפרופיל שלי",
    verification: "אימות חשבון",
    admin: "ניהול",
    emergency: "מספרי חירום",
    signOut: "התנתקות",
    signIn: "התחברות",
    signUp: "הרשמה",
  },

  auth: {
    email: "אימייל",
    password: "סיסמה",
    signInTitle: "התחברות ל-iHelp",
    signUpTitle: "הרשמה ל-iHelp",
    signInAction: "התחברות",
    signUpAction: "הרשמה",
    haveAccount: "כבר יש לך חשבון?",
    noAccount: "אין לך חשבון עדיין?",
    badCredentials: "אימייל או סיסמה שגויים",
    emailTaken: "כבר קיים חשבון עם האימייל הזה — נסו להתחבר",
    passwordHint: "לפחות 8 תווים",
  },

  profile: {
    title: "הפרופיל שלי",
    displayName: "שם תצוגה",
    phone: "טלפון",
    phoneNote: "הטלפון נחשף רק לצד השני לאחר שיבוץ לבקשה משותפת",
    location: "מיקום",
    locationSet: "מיקום שמור ✓",
    locationUnset: "לא הוגדר מיקום — בקשות יוצגו ללא מיון לפי מרחק",
    captureLocation: "עדכון מיקום נוכחי",
    locationDenied: "הרשאת מיקום נדחתה — אפשר להמשיך בלי מיון לפי מרחק",
    save: "שמירה",
    saved: "נשמר בהצלחה",
    onboardingHint: "כמעט סיימנו — נשאר רק לבחור שם תצוגה",
  },

  verification: {
    title: "אימות חשבון",
    explainer:
      "כדי לפרסם בקשות או להציע עזרה, נדרש אימות זהות חד-פעמי. מנהל בודק כל בקשה — משני הצדדים של כל עסקה עומד אדם מאומת.",
    identityTitle: "אימות זהות",
    professionalTitle: "תעודה מקצועית (רשות)",
    professionalExplainer:
      "בעלי מקצוע יכולים לצרף תעודה ולקבל תג ״בעל מקצוע״ שמוצג ליד ההצעות שלהם.",
    fullName: "שם מלא",
    selfDescription: "כמה מילים עליי",
    phone: "טלפון (נחשף רק לאחר שיבוץ)",
    idPhoto: "צילום תעודה מזהה (רשות — מחזק את הבדיקה)",
    certificate: "צילום תעודה מקצועית",
    submit: "שליחה לבדיקה",
    pending: "הבקשה בבדיקה — נעדכן כשתאושר",
    approved: "מאומת ✓",
    rejected: "הבקשה נדחתה",
    rejectedNote: "הערת המנהל",
    reapply: "הגשה מחדש",
    verifiedIdentity: "זהות מאומתת",
    professionalBadge: "בעל מקצוע",
    gateMessage: "פעולה זו דורשת אימות זהות — זה לוקח רק דקה",
  },

  requests: {
    feedTitle: "בקשות עזרה פתוחות",
    newRequest: "בקשת עזרה חדשה",
    title: "כותרת",
    description: "תיאור",
    category: "קטגוריה",
    allCategories: "כל הקטגוריות",
    paid: "בתשלום",
    volunteer: "בהתנדבות",
    photos: "תמונות (1–5)",
    photosHint: "תמונה טובה עוזרת לעוזרים להבין את המשימה לפני שהם מציעים",
    location: "מיקום הבקשה",
    locationConfirm: "אישור מיקום נוכחי",
    locationFromProfile: "ישתמש במיקום מהפרופיל",
    publish: "פרסום הבקשה",
    edit: "עריכה",
    saveChanges: "שמירת שינויים",
    cancelRequest: "ביטול הבקשה",
    cancelConfirm: "לבטל את הבקשה? כל ההצעות ייסגרו וזה סופי.",
    distanceUnknown: "ללא מיון מרחק",
    away: "ממך",
    mapTitle: "מיקום הבקשה",
    mapPickerHint: "לחצו על המפה כדי לסמן את מיקום הבקשה",
    mapAllTitle: "מפת הבקשות",
    viewRequest: "לצפייה בבקשה",
    showMap: "תצוגת מפה",
    hideMap: "הסתרת מפה",
    noOpenRequests: "אין בקשות פתוחות כרגע — פרסמו את הבקשה הראשונה!",
    myRequestsTitle: "הבקשות שלי",
    noMyRequests: "עוד לא פרסמת בקשות",
    postedAt: "פורסם",
    status: {
      open: "פתוחה",
      has_offers: "יש הצעות",
      assigned: "שובצה",
      completed: "הושלמה",
      rated: "דורגה",
      cancelled: "בוטלה",
    } as Record<string, string>,
    hidden: "הוסתרה על ידי מנהל",
  },

  offers: {
    sectionTitle: "הצעות",
    myOffersTitle: "ההצעות שלי",
    noOffersYet: "עוד אין הצעות — עוזרים באזור יראו את הבקשה בקרוב",
    noOffersFinal: "לא התקבלו הצעות",
    noMyOffers: "עוד לא הצעת עזרה",
    offerHelp: "הצעת עזרה",
    message: "איך אעזור",
    price: "המחיר שלי (₪)",
    priceHint: "השאירו ריק כדי להציע בהתנדבות",
    freeOffer: "בהתנדבות",
    pricingLabel: "המחיר שלי",
    modeFixed: "מחיר קבוע",
    modeVolunteer: "בהתנדבות (חינם)",
    modeAfterJob: "מחיר ייקבע לאחר העבודה",
    modeAfterJobHint: "מתאים כשאי אפשר לתמחר לפני שרואים את הבעיה — תזינו סכום בסיום",
    priceTBD: "מחיר ייקבע בסיום",
    setFinalPriceTitle: "קביעת המחיר הסופי",
    setFinalPriceHint: "העבודה הושלמה — הזינו את הסכום הסופי לתשלום",
    setFinalPriceSubmit: "קביעת מחיר",
    awaitingFinalPrice: "העוזר יקבע את המחיר הסופי בקרוב",
    submit: "שליחת הצעה",
    update: "עדכון ההצעה",
    withdraw: "משיכת ההצעה",
    withdrawConfirm: "למשוך את ההצעה?",
    choose: "בחירה בהצעה זו",
    chooseConfirm: "לבחור בהצעה זו? שאר ההצעות ייסגרו.",
    yourOffer: "ההצעה שלך",
    status: {
      active: "פעילה",
      selected: "נבחרה ✓",
      closed: "נסגרה",
      withdrawn: "נמשכה",
    } as Record<string, string>,
    requestGone: "הבקשה אינה זמינה עוד",
  },

  lifecycle: {
    contactTitle: "פרטי קשר לתיאום",
    contactExplainer: "הפרטים גלויים רק לשניכם. תאמו את העזרה ביניכם.",
    agreedPrice: "המחיר שסוכם",
    confirmCompletion: "אישור שהעזרה הושלמה",
    waitingOther: "ממתין לאישור הצד השני",
    youConfirmed: "אישרת ✓",
    otherConfirmed: "הצד השני אישר — נשאר רק האישור שלך",
    completedBoth: "העזרה הושלמה — שני הצדדים אישרו",
    markPaid: "סימון כשולם",
    markedPaid: "שולם ✓",
    rateTitle: "דירוג העוזר",
    rateNote: "הערה (רשות)",
    rateSubmit: "שליחת דירוג",
    rated: "תודה על הדירוג!",
    stars: "כוכבים",
  },

  helpers: {
    profileTitle: "פרופיל עוזר",
    ratingCount: "דירוגים",
    noRatings: "עדיין אין דירוגים",
  },

  admin: {
    title: "ניהול",
    queueTitle: "בקשות אימות ממתינות",
    queueEmpty: "אין בקשות ממתינות",
    kind: { identity: "אימות זהות", professional: "תעודה מקצועית" } as Record<
      string,
      string
    >,
    approve: "אישור",
    reject: "דחייה",
    noteLabel: "נימוק (חובה בדחייה)",
    historyTitle: "היסטוריית בקשות קודמות",
    statusLabel: {
      approved: "אושרה",
      rejected: "נדחתה",
      revoked: "בוטלה",
    } as Record<string, string>,
    moderationTitle: "בקשות עזרה — פיקוח",
    hide: "הסתרה",
    unhide: "ביטול הסתרה",
    revoke: "ביטול אימות",
    revokeConfirm: "לבטל את האימות של המשתמש?",
    viewDoc: "צפייה במסמך",
  },

  emergency: {
    title: "מספרי חירום",
    notice:
      "iHelp אינה שירות חירום. במצב חירום התקשרו ישירות למספרים האלה.",
    call: "חיוג",
    services: [
      { name: "משטרה", phone: "100" },
      { name: "מד\"א — מגן דוד אדום", phone: "101" },
      { name: "כיבוי והצלה", phone: "102" },
      { name: "ער\"ן — עזרה ראשונה נפשית", phone: "1201" },
      { name: "קו סיוע לנפגעות תקיפה מינית (נשים)", phone: "1202" },
      { name: "קו סיוע לנפגעי תקיפה מינית (גברים)", phone: "1203" },
    ],
  },

  common: {
    loading: "טוען…",
    back: "חזרה",
    notFoundTitle: "העמוד לא נמצא",
    notFoundBody: "יכול להיות שהקישור שגוי או שאין לך הרשאה לצפות בעמוד הזה.",
    errorTitle: "משהו השתבש",
    retry: "נסו שוב",
    landingCta: "לצפייה בבקשות",
    landingSignUp: "הצטרפות ל-iHelp",
  },
} as const;
